Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('report/', include('report.urls')),
    path('user/', include('userApp.urls')),
]






urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name='mainApp'
urlpatterns = [
    path('',views.home,name='home'),
    path('show_companies/',views.show_companies,name='show_companies'),
    path('show_items/',views.show_items,name='show_items'),





    path('checkUniquenessOfserial_start/',views.checkUniquenessOfserial_start,name='checkUniquenessOfserial_start'),
    path('checkUniquenessOfpart_num/',views.checkUniquenessOfpart_num,name='checkUniquenessOfpart_num'),
    

    # category
    path('listOf_category/',views.listOf_category,name='listOf_category'),
    path('get_all_categories_by_name/',views.get_all_categories_by_name,name='get_all_categories_by_name'),
    path('getListOf_category/',views.getListOf_category,name='getListOf_category'),
    path('addnew_category/',views.addnew_category,name='addnew_category'),
    path('delete_category/',views.delete_category,name='delete_category'),



    # item
    path('item_by_part_num/',views.item_by_part_num,name='item_by_part_num'),
    path('listOf_item/',views.listOf_item,name='listOf_item'),
    path('getListOf_item/',views.getListOf_item,name='getListOf_item'),
    path('addnew_item/',views.addnew_item,name='addnew_item'),
    path('show_item/',views.show_item,name='show_item'),
    path('delete_item/',views.delete_item,name='delete_item'),




    path('out_stock_item/',views.out_stock_item,name='out_stock_item'),
    path('return_stock_item/',views.return_stock_item,name='return_stock_item'),

    # path('gen_listOf_item/',views.gen_listOf_item,name='gen_listOf_item'),
    


    # factory
    path('listOf_factory/',views.listOf_factory,name='listOf_factory'),
    path('getListOf_factory/',views.getListOf_factory,name='getListOf_factory'),
    path('addnew_factory/',views.addnew_factory,name='addnew_factory'),
    path('delete_factory/',views.delete_factory,name='delete_factory'),


    
    # sector
    path('listOf_sector/',views.listOf_sector,name='listOf_sector'),
    path('getListOf_sector/',views.getListOf_sector,name='getListOf_sector'),
    path('addnew_sector/',views.addnew_sector,name='addnew_sector'),
    path('delete_sector/',views.delete_sector,name='delete_sector'),




    # tranche
    path('listOf_tranche/',views.listOf_tranche,name='listOf_tranche'),
    path('getListOf_tranche/',views.getListOf_tranche,name='getListOf_tranche'),
    path('addnew_tranche/',views.addnew_tranche,name='addnew_tranche'),
    path('delete_tranche/',views.delete_tranche,name='delete_tranche'),


    
    # company
    path('listOf_company/',views.listOf_company,name='listOf_company'),
    path('getListOf_company/',views.getListOf_company,name='getListOf_company'),
    path('addnew_company/',views.addnew_company,name='addnew_company'),
    path('delete_company/',views.delete_company,name='delete_company'),

]

report/urls.py
from django.urls import path
from . import views

app_name='report'
urlpatterns = [
    path('daily_report',views.daily_report,name='daily_report'),
    path('total_report',views.total_report,name='total_report'),

    
    path('export_daily_report',views.export_daily_report,name='export_daily_report'),
    path('export_total_report',views.export_total_report,name='export_total_report'),
    path('factory_needed_report',views.factory_needed_report,name='factory_needed_report'),
    path('factory_needed_report_by_factory',views.factory_needed_report_by_factory,name='factory_needed_report_by_factory'),
    

]

mainApp/views.py
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.shortcuts import render,redirect,reverse
from django.core.exceptions import SuspiciousOperation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
import json
from django.db.models import Count
from django.db.models import Q
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models.query import QuerySet

from django.utils.translation import activate, get_language
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import HttpResponseRedirect
from django.http import HttpResponse 
from django.db import connection
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.decorators.csrf import csrf_protect
from datetime import datetime, timedelta,date

from mainApp.models import *

from io import StringIO
import xlsxwriter
from django.http import HttpResponse


@login_required
def home(request):


    urlLink = reverse("mainApp:listOf_item")
    return redirect(urlLink)
    




@login_required
def show_companies(request):
    context = {
        
    }
    return render (request, 'elements/show_companies.html', context)

@login_required
def out_stock_item(request):
    all_color = color.objects.filter( Q(deleted_date=None))
    all_size = size.objects.filter( Q(deleted_date=None))
    all_company = company.objects.filter( Q(deleted_date=None))
    all_rep = User.objects.filter( Q(deleted=None) ,Q(role__id=2))
    

    if request.method=='POST':
        comp_or_rep = request.POST['comp_or_rep']


        try:
            if comp_or_rep=='1':
                company_withObject = request.POST['company_with']
                company_withObject = company.objects.get(id=company_withObject)
            else:
                company_withObject = None
        except:
            company_withObject = None
        

        try:
            if comp_or_rep=='0':
                representitive_withObject = request.POST['representitive_with']
                representitive_withObject = User.objects.get(id=representitive_withObject)
            else:
                representitive_withObject = None
        except:
            representitive_withObject = None


        jsonArray_part_num = request.POST['jsonArray_part_num']
        
        all_parts = json.loads(jsonArray_part_num)
        for part_num in all_parts:
            # print(part_num)
            try:
                filedetails = request.FILES['file_'+str(part_num)]
                attachmentTranscriptObject = attachmentTranscript.objects.create(file = filedetails,content_type=filedetails.content_type,name=filedetails.name,table_name="transaction")
                attachmentTranscriptObject.save()
            except:
                attachmentTranscriptObject = None
            
            try:
                note = request.POST['note_'+str(part_num)]
            except:
                note = ""


          

            itemObject = item.objects.filter(Q(part_num=part_num) & Q(exists=True) & Q(deleted_date=None))
            if itemObject is not None and len(itemObject)>0:
                # print("create")
                itemnew = item.objects.filter(Q(part_num=part_num) & Q(exists=True) & Q(deleted_date=None))[0]
                # itemnew = item.objects.get(id=itemnew.id)

                # print("create")
                type_of_transaction_object = type_of_transaction.objects.get(id=settings.ID_OUT_TYPE_OF_TRANSACTION)
                    
                # print("create")
                transactionObject = transaction.objects.create(
                    item = itemnew,
                    type_of_transaction = type_of_transaction_object,
                    image = attachmentTranscriptObject,
                    company = company_withObject,
                    representitive = representitive_withObject,
                    note = note,
                    created_by = request.user
                )
                transactionObject.save()
                itemObject.update(last_out_date=datetime.now(),company_with=company_withObject,representitive_with=representitive_withObject,exists=False,is_returned=False)
                
                # print("create")

            
        
        

    context = {
        'all_company':all_company,
        'all_color':all_color,
        'all_size':all_size,
        'all_rep':all_rep
        }

    return render (request, 'operations/out_stock_item.html', context)




@login_required
def return_stock_item(request):

    all_color = color.objects.filter( Q(deleted_date=None))
    all_size = size.objects.filter( Q(deleted_date=None))
    all_company = company.objects.filter( Q(deleted_date=None))
    all_rep = User.objects.filter( Q(deleted=None) ,Q(role__id=2))
    

    if request.method=='POST':
        
        # try:
        #     company_withObject = request.POST['company_with']
        #     company_withObject = company.objects.get(id=company_withObject)
        # except:
        #     company_withObject = None
        

        # try:
        #     representitive_withObject = request.POST['representitive_with']
        #     representitive_withObject = User.objects.get(id=representitive_withObject)
        # except:
        #     representitive_withObject = None


        jsonArray_part_num = request.POST['jsonArray_part_num']
        
        all_parts = json.loads(jsonArray_part_num)
        for part_num in all_parts:
            # print(part_num)
            try:
                filedetails = request.FILES['file_'+str(part_num)]
                attachmentTranscriptObject = attachmentTranscript.objects.create(file = filedetails,content_type=filedetails.content_type,name=filedetails.name,table_name="transaction")
                attachmentTranscriptObject.save()
            except:
                attachmentTranscriptObject = None
            
            try:
                note = request.POST['note_'+str(part_num)]
            except:
                note = None
            
            itemObject = item.objects.filter(Q(part_num=part_num) & Q(exists=False) & Q(deleted_date=None))
            if itemObject is not None and len(itemObject)>0:
                # print("create")
                itemnew = item.objects.filter(Q(part_num=part_num) & Q(exists=False) & Q(deleted_date=None))[0]
                try:
                    representitive_withObject = itemnew.representitive_with
                except:
                    representitive_withObject = None

                try:
                    company_withObject = itemnew.company_with
                except:
                    company_withObject = None
                # print("create")
                type_of_transaction_object = type_of_transaction.objects.get(id=settings.ID_RETURN_TYPE_OF_TRANSACTION)
                    
                # print("create")
                transactionObject = transaction.objects.create(
                    item = itemnew,
                    type_of_transaction = type_of_transaction_object,
                    image = attachmentTranscriptObject,
                    company = company_withObject,
                    representitive = representitive_withObject,
                    note = note,
                    created_by = request.user
                )
                transactionObject.save()
                
                
                itemObject.update(company_with=None,representitive_with=None,last_return_date=datetime.now(),exists=True,is_returned=True)
                
                

    context = {
        'all_company':all_company,
        'all_color':all_color,
        'all_size':all_size,
        'all_rep':all_rep
        }

    return render (request, 'operations/return_stock_item.html', context)








####################  category  #################3
@login_required
def listOf_category(request):
    
    return render(request,'category/list.html',None)


@login_required
def getListOf_category(request):
    pageLength = int(request.GET['length'])
    pageNumber = int(request.GET['start'])
    draw = int(request.GET['draw'])
    searchKey = request.GET['search[value]']
    pageNumber = int(pageNumber/pageLength + 1)
    
    try:
        if searchKey == '':
            allElements = category.objects.filter( Q(deleted_date=None))
        else:
            allElements = category.objects.filter(Q(deleted_date=None) & 
            (Q(name__contains=searchKey) |
             Q(name_en__contains=searchKey)|
             Q(color__name__contains=searchKey)|
             Q(color__name_en__contains=searchKey)|
             Q(factory__name__contains=searchKey)|
             Q(factory__name_en__contains=searchKey)|
             Q(serial_start__contains=searchKey)|
             Q(id__contains=searchKey) ))

        paginator = Paginator(allElements, pageLength)
        
        try:
            response = paginator.page(pageNumber)
        except PageNotAnInteger:
            response = paginator.page(pageNumber)
        except EmptyPage:
            response = paginator.page(paginator.num_pages)

        listResult = list(response)
        allElementsJson = {"draw": draw,"recordsTotal": len(allElements),"recordsFiltered": len(allElements),"data":[]}

        for result in listResult:
            allElementsJson['data'].append(result.to_json())

        return JsonResponse(allElementsJson)
    except Exception as e:
        print("Ahmed Error: "+str(e))
        return JsonResponse({"draw": draw,"recordsTotal": 0,"recordsFiltered": 0,"data":[]})


@login_required
def addnew_category(request):
    typeOfEntry = request.GET['type']
    if typeOfEntry == 'new':

mainApp/templates/factory/addnew.html
{% extends 'theme.html' %}
{%load static%}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}



{% block 'title' %}
  {% trans 'المصانع' %}
{% endblock %}


{% block 'content' %}


<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 style="float: right;"> 
          <ol class="breadcrumb float-sm-left">
            
            <li  class="breadcrumb-item"><a href="{%url 'mainApp:home'%}">{%  trans 'الصفحةالرئيسية'%}</a></li>
            <li  class="breadcrumb-item"><a href="{%url 'mainApp:listOf_factory'%}">{% trans 'قائمة المصانع'%}</a></li>
            <li class="breadcrumb-item active"> {% trans 'المصنع'%}</li>
          </ol>
         </h1>
      </div>
    </div>
  </div>
</section>




<div class="container post-listing">
    <!-- <input type="hidden" id="dataOfrole" value="{{roleDetails.id}}"> -->
    

    <div class="row ">
      <div class="col-md-12 col-xm-12 single-post">
        
       
        <div class="box-body">
            <div class="tab-content">
              <div class="tab-pane form-horizontal active" id="Listed">
                
               


                <!--Start of the Form-->
                <div dir="rtl" class="card">
                    <div class="card-header card-header-primary greenbar" style="text-align: justify;">
                      <h4 class="card-title">{%  trans 'اضافة مصنع'%}</h4>
                      <p class="card-category">{%  trans 'برجاء ادخال بيانات المصنع'%}</p>
                    </div>
                    <div class="card-body" style="text-align: justify;">
                      <form  method="POST" enctype="multipart/form-data" id="form" class="needs-validation form-horizontal" novalidate>
                        {% csrf_token %}

                        <div class="row">
                          <img id="profileCoverImg" class="h-100 w-100" src='{% if factoryData.image is None or factoryData.image == "" %}{% static "img/1920x400/img2.jpg" %}{% else %}{{factoryData.image.file.url}}{%endif%}' alt="Image Description">

                          <!-- Avatar -->
                          <label class="avatar avatar-xxl profile-cover-avatar p-0" for="image">
                            <img id="image_object" class="avatar-img" src='{% if factoryData.image is None or factoryData.image == "" %}{% static "img/160x160/img2.jpg" %}{% else %}{{factoryData.image.file.url}}{%endif%}' alt="Image Description">
              
                            <input type="file" class="js-file-attach avatar-uploader-input" name="image" id="image" data-hs-file-attach-options='{
                                        "textTarget": "#editAvatarImgModal",
                                        "mode": "image",
                                        "targetAttr": "src",
                                        "allowTypes": [".png", ".jpeg", ".jpg"]
                                    }'>
              
                            <span class="avatar-uploader-trigger">
                              <i class="bi-pencil-fill avatar-uploader-icon shadow-sm"></i>
                            </span>
                          </label>
                          <!-- End Avatar -->
                        </div>


                        <div class="row">
                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="name">{%  trans 'اسم الهيئة'%}</label>
                              <input type="hidden" id="id" name="id" value="{{factoryData.id}}">
                              <input type="text" required="" class="form-control required mb-3"  name="name" value="{{factoryData.name}}" id="name">
                              <div class="invalid-feedback">
                                {%  trans 'الرجاء التحقق من هذه الخانة'%}
                              </div>  
                            </div>
                            <div id="usernameError">

                            </div>
                          </div>



                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="name_en">{%  trans 'الاسم بالإنجليزية'%}</label>
                              <input type="text" required="" class="form-control required mb-3" name="name_en" value="{{factoryData.name_en}}" id="name_en">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال هذا الحقل'%}
                              </div>  
                            </div>
                          </div>


                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="head_phone">{%  trans 'هاتف المدير'%}</label>
                              <input type="tel" required="" class="form-control required mb-3" name="head_phone" value="{{factoryData.head_phone}}" id="head_phone">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال هذا الحقل'%}
                              </div>  
                            </div>
                          </div>
                        
                        </div>


                        <div class="row">
                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="factory_phone">{%  trans 'رقم هاتف الشركة'%}</label>
                              <input type="factory_phone" required=""  class="form-control required mb-3" name="factory_phone" value="{{factoryData.factory_phone}}" id="factory_phone">
                              <div class="invalid-feedback">
                                {%  trans 'الرجاء التحقق من هذه الخانة'%} 
                              </div>  
                            </div>
                          </div>
                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="tax_number">{%  trans 'الرقم الضريبى'%}</label>
                              <input type="text"   class="form-control " name="tax_number" value="{{factoryData.tax_number}}" id="tax_number">
                              <div class="invalid-feedback">
                                {%  trans 'الرجاء التحقق من هذه الخانة'%} 
                              </div>  
                            </div>
                          </div>

                          <div class="col-12 col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="address">{%  trans 'العنوان'%}</label>
                              <input type="text" required=""  class="form-control required mb-3" name="address" value="{{factoryData.address}}" id="address">
                              <div class="invalid-feedback">
                                {%  trans 'الرجاء التحقق من هذه الخانة'%} 
                              </div>  
                            </div>

                          </div>
                        </div>



                     


                     
                        
                    
                      
                         
                        <br/>
                        <!-- <button type="submit" class="btn btn-primary pull-right">حفظ</button> -->
                        <button type="submit" class="btn btn-primary" >{% trans "Save" %}</button>

                        <div class="clearfix"></div>
                      </form>
                    </div>
                  </div>

                <!--End of the Form-->

              </div>
            </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}




{% block javaNew %}


<script>

(function() {
    'use strict';
    window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
    form.addEventListener('submit', function(event) {
    if (form.checkValidity() === false) {
    event.preventDefault();
    event.stopPropagation();
    }
    form.classList.add('was-validated');
    }, false);
    });
    }, false);
    })();





// new functionality on submit checking if the factory name doesn't exist before 







</script>
 

<script>

  
    
document.getElementById('image').onchange = function (evt) {

    var tgt = evt.target || window.event.srcElement,
        files = tgt.files;

    // FileReader support
    if (FileReader && files && files.length) {
        var fr = new FileReader();
        fr.onload = function () {
            document.getElementById('image_object').src = fr.result;
        }
        fr.readAsDataURL(files[0]);
    }

    // Not supported
    else {
        // fallback -- perhaps submit the input to an iframe and temporarily store
        // them on the server until the user's session ends.
    }
}


</script>
   



<script>
  $('#navbar_enter_data_main').removeClass('collapsed')
  $('#navbar_enter_data').addClass('show')
  $('#navbar_enter_data_main').attr('aria-expanded','true')
  $('#listOf_factory').addClass('active')
</script>
{% endblock %}