Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('report/', include('report.urls')),
    path('user/', include('userApp.urls')),
]






urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name='mainApp'
urlpatterns = [
    path('',views.home,name='home'),
    path('show_companies/',views.show_companies,name='show_companies'),
    path('show_items/',views.show_items,name='show_items'),





    path('checkUniquenessOfserial_start/',views.checkUniquenessOfserial_start,name='checkUniquenessOfserial_start'),
    path('checkUniquenessOfpart_num/',views.checkUniquenessOfpart_num,name='checkUniquenessOfpart_num'),
    

    # category
    path('listOf_category/',views.listOf_category,name='listOf_category'),
    path('get_all_categories_by_name/',views.get_all_categories_by_name,name='get_all_categories_by_name'),
    path('getListOf_category/',views.getListOf_category,name='getListOf_category'),
    path('addnew_category/',views.addnew_category,name='addnew_category'),
    path('delete_category/',views.delete_category,name='delete_category'),



    # item
    path('item_by_part_num/',views.item_by_part_num,name='item_by_part_num'),
    path('listOf_item/',views.listOf_item,name='listOf_item'),
    path('getListOf_item/',views.getListOf_item,name='getListOf_item'),
    path('addnew_item/',views.addnew_item,name='addnew_item'),
    path('show_item/',views.show_item,name='show_item'),
    path('delete_item/',views.delete_item,name='delete_item'),




    path('out_stock_item/',views.out_stock_item,name='out_stock_item'),
    path('return_stock_item/',views.return_stock_item,name='return_stock_item'),

    # path('gen_listOf_item/',views.gen_listOf_item,name='gen_listOf_item'),
    


    # factory
    path('listOf_factory/',views.listOf_factory,name='listOf_factory'),
    path('getListOf_factory/',views.getListOf_factory,name='getListOf_factory'),
    path('addnew_factory/',views.addnew_factory,name='addnew_factory'),
    path('delete_factory/',views.delete_factory,name='delete_factory'),


    
    # sector
    path('listOf_sector/',views.listOf_sector,name='listOf_sector'),
    path('getListOf_sector/',views.getListOf_sector,name='getListOf_sector'),
    path('addnew_sector/',views.addnew_sector,name='addnew_sector'),
    path('delete_sector/',views.delete_sector,name='delete_sector'),




    # tranche
    path('listOf_tranche/',views.listOf_tranche,name='listOf_tranche'),
    path('getListOf_tranche/',views.getListOf_tranche,name='getListOf_tranche'),
    path('addnew_tranche/',views.addnew_tranche,name='addnew_tranche'),
    path('delete_tranche/',views.delete_tranche,name='delete_tranche'),


    
    # company
    path('listOf_company/',views.listOf_company,name='listOf_company'),
    path('getListOf_company/',views.getListOf_company,name='getListOf_company'),
    path('addnew_company/',views.addnew_company,name='addnew_company'),
    path('delete_company/',views.delete_company,name='delete_company'),

]

report/urls.py
from django.urls import path
from . import views

app_name='report'
urlpatterns = [
    path('daily_report',views.daily_report,name='daily_report'),
    path('total_report',views.total_report,name='total_report'),

    
    path('export_daily_report',views.export_daily_report,name='export_daily_report'),
    path('export_total_report',views.export_total_report,name='export_total_report'),
    path('factory_needed_report',views.factory_needed_report,name='factory_needed_report'),
    path('factory_needed_report_by_factory',views.factory_needed_report_by_factory,name='factory_needed_report_by_factory'),
    

]

userApp/urls.py
from django.urls import path
from . import views

app_name='userApp'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('checkUniquenessOfUsername/',views.checkUniquenessOfUsername,name='checkUniquenessOfUsername'),

    
    path('listOf_user/',views.listOf_user,name='listOf_user'),
    path('getListOf_user/',views.getListOf_user,name='getListOf_user'),
    path('addnew_user/',views.addnew_user,name='addnew_user'),
    path('delete_user/',views.delete_user,name='delete_user'),


    
    path('listOf_role/',views.listOf_role,name='listOf_role'),
    path('getListOf_role/',views.getListOf_role,name='getListOf_role'),
    path('addnew_role/',views.addnew_role,name='addnew_role'),


    
]

userApp/forms.py
from django import forms




class userLogin(forms.Form):
    username = forms.CharField(max_length=100,required=True,widget= forms.TextInput(attrs={'class':'form-control form-control-lg','placeholder':' username','id':'signinSrusername','tabindex':'1','aria-label':'username'}))
    password = forms.CharField(max_length=100,required=True,widget=forms.PasswordInput(attrs={'class':'js-toggle-password form-control form-control-lg','placeholder':'  password','id':'signupSrPassword','placeholder':'3+ characters required','aria-label':'3+ characters required','minlength':'3','data-hs-toggle-password-options':'''{
                           "target": "#changePassTarget",
                           "defaultClass": "bi-eye-slash",
                           "showClass": "bi-eye",
                           "classChangeTarget": "#changePassIcon"
                         }'''}))


    

userApp/views.py
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.shortcuts import render,redirect,reverse
from django.core.exceptions import SuspiciousOperation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
import json
from django.db.models import Count
from django.db.models import Q
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models.query import QuerySet

from django.utils.translation import activate, get_language
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.decorators.csrf import csrf_protect
from datetime import datetime, timedelta,date

from mainApp.models import *
from userApp.models import *

from .forms import *

# @unauthenticated_user
def user_login(request):
    
    if request.method=='POST':
        loginform=userLogin(request.POST)

        if loginform.is_valid():
            username=request.POST['username']
            password=request.POST['password']
            print(username)
            print(password)
            user=authenticate(username=username,password=password)
            print(user)
            if user is not None: 
                # print("Exists")
                login(request,user)
                links = request.META['HTTP_REFERER'].split('next=')
                # print( links[1] )
                try:
                    return redirect(links[1])
                except:
                    return redirect("/")
        return render(request,"login.html",{'form':loginform,'flag':True})

    else:
        loginform=userLogin()
        return render(request,"login.html",{'form':loginform})


def user_logout(request):
    logout(request)
    return redirect("userApp:login")


####################  role  #################3
@login_required
def listOf_role(request):
    
    return render(request,'role/list.html',None)


@login_required
def getListOf_role(request):
    pageLength = int(request.GET['length'])
    pageNumber = int(request.GET['start'])
    draw = int(request.GET['draw'])
    searchKey = request.GET['search[value]']
    pageNumber = int(pageNumber/pageLength + 1)
    
    try:
        if searchKey == '':
            allElements = role.objects.filter( Q(id__isnull=False))
        else:
            allElements = role.objects.annotate(permissionGeneralCount=Count('permissionGeneral')).filter(Q(deleted=False) & 
            (Q(name__contains=searchKey) | Q(name_en__contains=searchKey) | Q(permissionGeneralCount__contains=searchKey)|
             Q(id__contains=searchKey) ))


        if pageLength == -1:
            if allElements !=None:
                pageLength = len(allElements)

        paginator = Paginator(allElements, pageLength)
        
        try:
            response = paginator.page(pageNumber)
        except PageNotAnInteger:
            response = paginator.page(pageNumber)
        except EmptyPage:
            response = paginator.page(paginator.num_pages)

        listResult = list(response)
        allElementsJson = {"draw": draw,"recordsTotal": len(allElements),"recordsFiltered": len(allElements),"data":[]}

        for result in listResult:
            allElementsJson['data'].append(result.to_json())

        return JsonResponse(allElementsJson)
    except Exception as e:
        print("Ahmed Error: "+str(e))
        return JsonResponse({"draw": draw,"recordsTotal": 0,"recordsFiltered": 0,"data":[]})


@login_required
def addnew_role(request):
    typeOfEntry = request.GET['type']
    if typeOfEntry == 'new':
        allSelectedPermissions = None
        dataToInsert = None
    elif typeOfEntry == 'edit':
        idOfelement = request.GET['id']
        dataToInsert = role.objects.get(id=idOfelement)
        allselectedData=dataToInsert.permissionGeneral.all()
        allSelectedPermissions=[]
        for data in allselectedData:
            allSelectedPermissions.append(data.id)

             

    
    query = permissionGeneral.objects.values('number','mainNameAr','mainNameEn').annotate(mainNumber=Count('number')).filter(id__isnull=False)
    
    all_permissionGeneral = []
    for itemPermission in query:
        itemNew = {
                    'number':itemPermission['number'],
                    'mainNameAr':itemPermission['mainNameAr'],
                    'mainNameEn':itemPermission['mainNameEn'],
                    'allPermissionsRelated':[]
                }
        allPermissionForMain = permissionGeneral.objects.filter(Q(number=itemPermission['number']))
        for itemSmallPermission in allPermissionForMain:
            itemNew['allPermissionsRelated'].append(itemSmallPermission.to_json())


        all_permissionGeneral.append(itemNew)

        
    
    context = {
        'thisElementData':dataToInsert,
        'all_permissionGeneral':all_permissionGeneral,
        'allSelectedPermissions':allSelectedPermissions
        }
    if request.method=='POST':
        # print(request.POST)
        numberOfPermission = len(all_permissionGeneral)
        nameData = request.POST['name']
        name_enData = request.POST['name_en']
       


        permissionGeneralCheckBox = request.POST.getlist('permissionGeneralCheckBox')



        


        
        if typeOfEntry == 'new':

            

            dataToInsert = role.objects.create(name=nameData,name_en=name_enData)
            dataToInsert.save()
            for item in permissionGeneralCheckBox:
                subObject = permissionGeneral.objects.get(id=item)
                dataToInsert.permissionGeneral.add(subObject)
        elif typeOfEntry == 'edit':
            # role_parts.objects.filter(id=idOfelement).update(name=nameData,role=role_Data)

            dataToInsert.permissionGeneral.clear()
            for item in permissionGeneralCheckBox:
                subObject = permissionGeneral.objects.get(Q(id=str(item)))
                dataToInsert.permissionGeneral.add(subObject)
            
            dataToInsert = role.objects.filter(id=idOfelement)
            dataToInsert.update(name = nameData)


        urlLink = reverse("userApp:listOf_role")
        return redirect(urlLink)
    elif request.method=='GET':
        return render(request,'role/addnew.html',context)
    



####################  User  #################3
@login_required
def listOf_user(request):
    
    return render(request,'user/list.html',None)


@login_required
def getListOf_user(request):
    pageLength = int(request.GET['length'])
    pageNumber = int(request.GET['start'])
    draw = int(request.GET['draw'])
    searchKey = request.GET['search[value]']
    pageNumber = int(pageNumber/pageLength + 1)
    
    try:
        if searchKey == '':
            allElements = User.objects.filter( Q(deleted=None))
        else:
            allElements = User.objects.filter(Q(deleted=None) & 
            (Q(username__contains=searchKey) |
             Q(role__name__contains=searchKey)|
             Q(role__name_en__contains=searchKey)|
             Q(email__contains=searchKey)|
             Q(id_number__contains=searchKey)|
             Q(id__contains=searchKey) ))

        paginator = Paginator(allElements, pageLength)
        
        try:
            response = paginator.page(pageNumber)
        except PageNotAnInteger:
            response = paginator.page(pageNumber)
        except EmptyPage:
            response = paginator.page(paginator.num_pages)

        listResult = list(response)
        allElementsJson = {"draw": draw,"recordsTotal": len(allElements),"recordsFiltered": len(allElements),"data":[]}

        for result in listResult:
            allElementsJson['data'].append(result.to_json())

        return JsonResponse(allElementsJson)
    except Exception as e:
        print("Ahmed Error: "+str(e))
        return JsonResponse({"draw": draw,"recordsTotal": 0,"recordsFiltered": 0,"data":[]})


@login_required
def addnew_user(request):
    all_role = role.objects.all()
    typeOfEntry = request.GET['type']
    if typeOfEntry == 'new':
        dataToInsert = None
    elif typeOfEntry == 'edit':
        idOfelement = request.GET['id']
        dataToInsert = User.objects.get(id=idOfelement)
    
    
    context = {
        'all_role':all_role,
        'UserData':dataToInsert,
        'type':typeOfEntry}

    if request.method=='POST':
        emailData = request.POST['email']
        passwordData = request.POST['password']
        addressData = request.POST['address']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phoneData = request.POST['phone']
        role_Id = request.POST['role']
        id_number = request.POST['id_number']
        

      

      
        
        try:
            filedetails = request.FILES['image']

        except Exception as err:
            print("----------------------")
            print(err)
            if typeOfEntry == 'edit':
                filedetails = dataToInsert.image.file
            else:
                filedetails = None
        if filedetails is None or filedetails == "":
            try:
                filedetails = dataToInsert.image.file
            except:
                filedetails = None

 

        if role_Id !='':
            role_Data = role.objects.get(id=role_Id)
        else:
            role_Data = None

        if typeOfEntry == 'new':
            try:
                attachmentTranscriptObject = attachmentTranscript.objects.create(file = filedetails,content_type=filedetails.content_type,name=filedetails.name,table_name="user")
                attachmentTranscriptObject.save()
            except:

userApp/templates/user/addnew.html
{% extends 'theme.html' %}
{%load static%}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}



{% block 'title' %}
  {% trans 'المستخدمين' %}
{% endblock %}


{% block 'content' %}


<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 style="float: right;"> 
          <ol class="breadcrumb float-sm-left">
            
            <li  class="breadcrumb-item"><a href="{%url 'mainApp:home'%}">{%  trans 'الصفحةالرئيسية'%}</a></li>
            <li  class="breadcrumb-item"><a href="{%url 'userApp:listOf_user'%}">{% trans 'قائمة المستخدمين'%}</a></li>
            <li class="breadcrumb-item active"> {% trans 'المستخدمين'%}</li>
          </ol>
         </h1>
      </div>
    </div>
  </div>
</section>




<div class="container post-listing">
    <!-- <input type="hidden" id="dataOfrole" value="{{roleDetails.id}}"> -->
    

    <div class="row ">
      <div class="col-md-12 col-xm-12 single-post">
        
       
        <div class="box-body">
            <div class="tab-content">
              <div class="tab-pane form-horizontal active" id="Listed">
                
               


                <!--Start of the Form-->
                <div dir="rtl" class="card">
                    <div class="card-header card-header-primary greenbar" style="text-align: justify;">
                      <h4 class="card-title">{%  trans 'اضافة مستخدم'%}</h4>
                      <p class="card-category">{%  trans 'برجاء ادخال بيانات المستخدم'%}</p>
                    </div>
                    <div class="card-body" style="text-align: justify;">
                      <form  method="POST" enctype="multipart/form-data" id="form" class="needs-validation form-horizontal" novalidate>
                        {% csrf_token %}

                        <div class="row">
                         
                          <!-- Avatar -->
                          <label class="avatar avatar-xxl profile-cover-avatar p-0" for="image">
                            <img id="image_object" class="avatar-img" src='{% if UserData.image is None or UserData.image == "" %}{% static "img/160x160/img1.jpg" %}{% else %}{{UserData.image.file.url}}{%endif%}' alt="Image Description">
              
                            <input type="file" class="js-file-attach avatar-uploader-input" name="image" id="image" data-hs-file-attach-options='{
                                        "textTarget": "#editAvatarImgModal",
                                        "mode": "image",
                                        "targetAttr": "src",
                                        "allowTypes": [".png", ".jpeg", ".jpg"]
                                    }'>
              
                            <span class="avatar-uploader-trigger">
                              <i class="bi-pencil-fill avatar-uploader-icon shadow-sm"></i>
                            </span>
                          </label>
                          <!-- End Avatar -->
                        </div>


                        <div class="row">
                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="username">{%  trans 'اسم المستخدم'%}</label>
                              <input type="hidden" id="id" name="id" value="{{UserData.id}}">
                              <input type="text" required="" class="form-control required mb-3" {% if type == 'edit' %} disabled {% endif %} name="username" value="{{UserData.username}}" id="username">
                              <div class="invalid-feedback">
                                {%  trans ' برجاء ادخال اسم المستخدم '%}
                              </div>  
                            </div>
                            <div id="usernameError" class="rounded bg-danger p-2 mb-2 d-none">

                            </div>
                          </div>



                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="first_name">{%  trans 'الاسم الأول'%}</label>
                              <input type="text" required="" class="form-control required mb-3" name="first_name" value="{{UserData.first_name}}" id="first_name">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال هذا الحقل'%}
                              </div>  
                            </div>
                          </div>


                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="last_name">{%  trans 'الاسم الأخير'%}</label>
                              <input type="text" required="" class="form-control required mb-3" name="last_name" value="{{UserData.last_name}}" id="last_name">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال هذا الحقل'%}
                              </div>  
                            </div>
                          </div>
                        
                        </div>


                        <div class="row">
                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="email">{%  trans 'البريد الالكترونى'%}</label>
                              <input type="email" required=""  class="form-control required mb-3" name="email" value="{{UserData.email}}" id="email">
                              <div class="invalid-feedback">
                                {%  trans ' برجاء ادخال البريد الالكترونى '%} 
                              </div>  
                            </div>
                            <div id="emailError"></div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="password">{%  trans 'الرقم السرى'%}</label>
                              <input type="password"   class="form-control " name="password" value="" id="password">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال رقم الرقم السرى '%} 
                              </div>  
                            </div>
                          </div>

                          <div class="col-md-4">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="phone">{%  trans 'رقم الهاتف'%}</label>
                              <input type="tel" required=""  class="form-control required mb-3" name="phone" value="{{UserData.phone}}" id="phone">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال رقم الهاتف '%} 
                              </div>  
                            </div>
                            <div id="phoneError"></div>

                          </div>
                        </div>



                        <div class="row">
                          <div class="col-md-12">
                            <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="address">{%  trans 'العنوان'%}</label>
                              <input type="text" required=""  class="form-control required mb-3" name="address" value="{{UserData.address}}" id="address">
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال العنوان '%} 
                              </div>  
                            </div>
                          </div>
                        </div>


                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                            <label  class="pb-1" for="role">{%  trans '* صلاحية البيانات '%} </label>
                            <select required="" type="text" class="form-control required mb-3" name="role" value="{{UserData.role.id}}" id="role">
                                <option value="">{%  trans 'اختر احد الأنواع'%}</option>
                                {% for item in all_role %}
                                <option value="{{item.id}}"  {% if item.id == UserData.role.id %} selected {% endif %}>{{item.name}}</option>
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">
                              {%  trans 'برجاء اختيار احد الصلاحيات'%}
                            </div>  
                        </div>
                          
                        </div>




                        <div class="col-md-6">
                          <div class="form-group bmd-form-group">
                              <label  class="pb-1" for="id_number">{%  trans '* رقم البطاقة'%} </label>
                              <input type="number" required=""  class="form-control required mb-3" name="id_number" value="{{UserData.id_number}}" id="id_number">
                                
                              <div class="invalid-feedback">
                                {%  trans 'برجاء ادخال ادخال البطاقة'%}
                              </div>  
                          </div>
                          
                        </div>
                    </div>

                        
                    
                      
                         
                        <br/>
                        <!-- <button type="submit" class="btn btn-primary pull-right">حفظ</button> -->
                        <button type="submit" class="btn btn-primary" >{% trans "Save" %}</button>

                        <div class="clearfix"></div>
                      </form>
                    </div>
                  </div>

                <!--End of the Form-->

              </div>
            </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}




{% block javaNew %}


<script>

(function() {
    'use strict';
    window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
    form.addEventListener('submit', function(event) {

    if (form.checkValidity() === false) {
    event.preventDefault();
    event.stopPropagation();
    }else{
      let _this = $(this)
      
    event.preventDefault();
    event.stopPropagation();
        var username = $('#username').val()
        var id =  $('#id').val()


        console.log('-------------------')
     
      $.ajax({ 
        type: 'POST',
        url: '{% url "userApp:checkUniquenessOfUsername"%}',
        dataType: 'json',
        data: { 
            'username':username,
            'id':id,
        },
        headers:{
            "X-CSRFToken": csrftoken
                },
        async: true,
        cache: true,
        success: function(result) {
          // console.log(result[nameExists],"*********************************888888888888888")
          console.log(result['nameExists'],"*********1")
          if(result['nameExists'] == true){
            $('#usernameError').empty()
              $('#usernameError').removeClass('d-none')

            $('#usernameError').append("{% trans 'اسم المستخدم موجود بالفعل*'%}")
          } 
          else{
            console.log("not exists ")
              $('#usernameError').addClass('d-none')
            if ( $('form')[0].checkValidity() ) {
              $('#usernameError').empty()
            _this.unbind('submit').submit();

                          }

          }


        },
          
    });


    }
    form.classList.add('was-validated');
    }, false);
    });
    }, false);
    })();





// new functionality on submit checking if the user name doesn't exist before 









</script>
          

<script>

  
    
  document.getElementById('image').onchange = function (evt) {
  
      var tgt = evt.target || window.event.srcElement,
          files = tgt.files;
  
      // FileReader support
      if (FileReader && files && files.length) {
          var fr = new FileReader();
          fr.onload = function () {
              document.getElementById('image_object').src = fr.result;
          }
          fr.readAsDataURL(files[0]);
      }
  
      // Not supported
      else {
          // fallback -- perhaps submit the input to an iframe and temporarily store
          // them on the server until the user's session ends.
      }
  }
  
  
  </script>
   <script>
    $('#navbar_users_main').removeClass('collapsed')
    $('#navbar_users').addClass('show')
    $('#navbar_users_main').attr('aria-expanded','true')
    $('#listOf_user').addClass('active')
  </script>
{% endblock %}